---
title: "Stat- tests"
author: "theodoros foskolos"
date: "2023-09-08"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
```

# LAB 2 -Android runner

```{r}
#regural expressions can be checked on regex101
csv_paths <- list.files(path= "./data",
             recursive = TRUE, # recursive checks all the sub_directories
             pattern = "^Joule.*\\.csv",
             full.names = TRUE)
```

```{r}
app_data <- csv_paths %>%
  lapply(read_csv) %>%
  bind_rows
app_data

```

```{r}
# add experiment based on experiment name
app_data["experiment"] <- c(rep('cpu_test',10),
                            rep('display_test',10),
                            rep('speaker_test',10)
                            )

```

```{r}
app_data$experiment <- as.factor(app_data$experiment)

```

```{r}
# to do it based on the names with string split
app_data["experiment"] <- csv_paths%>%
  strsplit('-', fixed = TRUE) %>%
  rapply(nth, n=8)%>%
  factor
app_data

```

```{r}
app_data %>%
  group_by(experiment)%>%
  summarize(n=n(),
            mean = mean(Joule_calculated),
            median = median(Joule_calculated),
            sd = sd (Joule_calculated),
            IQR = IQR (Joule_calculated),
            min = min (Joule_calculated),
            max = max (Joule_calculated)
            )
```

```{r}
# breaks are the bins
app_data$Joule_calculated %>%
  hist(breaks = 25, main = 'Distribution of Joule_calculated')
# breaks are used for the bins
```

```{r}
# Linear Model with no main effects
Simple_interaction <- lm(Joule_calculated ~ experiment, data = app_data)
summary(Simple_interaction)
```

```{r}
boxplot(Joule_calculated ~ experiment,data=app_data, main="Joule per experiment",
   xlab="experiment", ylab="Energy_J")
```

```{r}
# lets say we simulate runtime as an extra variable
set.seed(123)
app_data$run_time <- round(runif(30, 10, 20), 2)

# Linear Model with Interaction
fit_interaction <- lm(Joule_calculated ~ experiment * run_time, data = app_data)
summary(fit_interaction)
```

```{r}
anova(fit_interaction)
```

```{r}
# gg plot is part of the tidyverse ( you can also import it with library (ggplot))
ggplot(app_data, aes(x=run_time, y=Joule_calculated, color=experiment)) +
  geom_point() +
  geom_smooth(method="lm", se=FALSE) +
  labs(title="Interaction Effect of Experiment Type and Run Time on Joule Calculated",
       x="Run Time",
       y="Joule Calculated",
       color="Experiment Type")

```

# Statistical tests - Parametric tests for normal distribution

```{r}
app_data%>%
  filter(experiment != 'cpufactorialtest')%>% 
  t.test(Joule_calculated ~ experiment, data=.)
```

```{r}
# aov  function analysis of variance
res.aov <- app_data%>%
  aov(Joule_calculated~experiment, data=.)
res.aov
```

The sum of squares for the **`experiment`** factor is significantly larger than that of the residuals, suggesting that the **`experiment`** factor explains a good portion of the variance in **`Joule_calculated`**.

```{r}
summary(res.aov)
```

# Non parametric - rank based test, if the data do not follow normal distribution

```{r}
#Kruskal wallis rank sum test
# One way anova on ranks ( alternative to the anova )
res.kruskal <- app_data%>%
  kruskal.test(Joule_calculated~experiment, data=.)
res.kruskal
```

```{r}
require(rstatix) # Various stat-tests
```

```{r}
# analysis of variance and t-tests for large amount of groups or factor levels
df_stats<- app_data%>%
   rstatix::wilcox_test(Joule_calculated~experiment, data=.)
df_stats
```

```{r}
# Paired t-test
t_test<- app_data%>%
  rstatix::t_test(Joule_calculated~experiment, data=., paired = TRUE)
t_test
```

```{r}
# evaluate effect size with kruskal effect size
#Effect size is a measure that quantifies the magnitude or strength of the relationship between variables or the impact of an intervention in stat analysis
efsize_df <- app_data%>%
  rstatix::kruskal_effsize(Joule_calculated~experiment, data=.)
efsize_df
```
